name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    name: Create Release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: teloscope ${{ github.ref_name }}
        generate_release_notes: true
        draft: false
        prerelease: false

  add_resources:
    needs: create_release
    name: Add Resources
    permissions: write-all
    strategy:
      matrix:
        OS: [macos-latest, ubuntu-latest, windows-2025]
        include:
        - OS: macos-latest
          OS_NAME: macOS
        - OS: ubuntu-latest
          OS_NAME: linux
        - OS: windows-2025
          OS_NAME: win
    runs-on: ${{ matrix.OS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: true
      - name: Build
        run: make
      - name: Zip
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            powershell Compress-Archive -Path build/bin/teloscope* -DestinationPath result.zip
          else
            zip -j result.zip build/bin/teloscope*
          fi
        shell: bash
      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: result.zip
          asset_name: teloscope.${{ github.ref_name }}-${{matrix.OS_NAME}}.zip

  add_submodules:
    needs: create_release
    name: Source with submodules
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: true
      - name: Zip
        run: zip -r result.zip .
      - name: Upload source
        uses: softprops/action-gh-release@v2
        with:
          files: result.zip
          asset_name: teloscope.${{ github.ref_name }}-with_submodules.zip
